### ISSUE TITLE
Improvement: Add fix flag to gulp-eslint task

### ISSUE THREAD

**Issue by awolkers** [mirabeau-nl/frontend-bootstrap#20]
When added/supprted, add the auto fix flag to the eslint task.
https://github.com/adametry/gulp-eslint/issues/99

The --fix command line option tells ESLint to attempt to automatically fix as many problems as possible. Fixes are only applied when it is safe to do so, and you’ll see any problems that were left unfixed. So now instead of going back into your files to insert a missing semicolon or properly indent some code, ESLint can do it for you.

**Comment by branneman** [comment]
Awesome :+1:

**Comment by awolkers** [comment]
feature added when eslint was upgraded to version 3.x e92d381b9e217427f1bb30d68e2b3c71b938412d
