### ISSUE TITLE
Data structured markup 

### ISSUE THREAD

**Issue by wouterkroes** [mirabeau-nl/frontend-bootstrap#21]
Schema.com/data structured markup is a way to help the search engines better index and understand the context of the website. This then gives a better experience in the search engine, voice search or maps e.g.
For more information see https://developers.google.com/structured-data/

Therefore I would like to add data structured markup code to the Bootstrap. 

Logo:
https://developers.google.com/structured-data/customize/logos

Social profile:
https://developers.google.com/structured-data/customize/social-profiles
Please note: "We encourage you to specify other social profiles as well, but they aren't currently included in Google search results."

Contact info:
https://developers.google.com/structured-data/customize/contact-points

Site Name:
https://developers.google.com/structured-data/site-name

Although the data/link is variable per project, I still think it is a good thing to have the code by default. "Forcing" developers to set the correct data/links and give the search engine/user the best experience. 
Question: Maybe there is a way to force to fill/remove the data when using the bootstrap?

I would suggest putting all of the above code/options (site name, contact info, social rule etc) in the ld+json format in the </head>. Then include this data-structured-markup file using the templating language. 

What do you guys think?

**Comment by awolkers** [comment]
How do you want to integrate this within the bootstrap? Does the code need to go within the head (via an external link) or do we embed the code within de html via the microdata format?

How do we enforce developer from entering the correct data when starting a new project?

**Comment by wouterkroes** [comment]
For the intergration in the bootstrap, I would suggest setting the site's global/constant settings in the </head>, i have made a example @ http://codepen.io/wouterk21/pen/vNJxMx

How to enforce the developer, i do not have a clear answer to this. Maybe a questionary during npm install? A reminder in the landing page of the installed bootstrap?

**Comment by ericweerstra** [comment]
The Mirabeau Frontend Bootstrap is meant for kickstarting your project by automating the install, watch, build and optionally the deploy process. 
There are a few basic code examples within the Bootstrap but its never intended as a Boilerplate with a lot of code examples. Therefore, data structured markup or other code examples and snippets are not within the scope of this project. I think it wil be hard to maintain and eventually become a mess if you keep adding different kind of code examples. Maybe it's an idea to start a Mirabeau Frontend Boilerplate for enhancing the Mirabeau Frontend Bootstrap?

**Comment by wouterkroes** [comment]
You have a point there Eric, maybe the bootstrap is not the correct place to place the code.
But the idea of a boilerplate sounds good, lemme think about it ;)

**Comment by awolkers** [comment]
@ericweerstra good point but we have to decide what the baseline is. What do we include and what is considered boilerplate content.

**Comment by branneman** [comment]
Closing because:
> the bootstrap is not the correct place to place this code
