### ISSUE TITLE
Gulp task sassdoc

### ISSUE THREAD

**Issue by wouterkroes** [mirabeau-nl/frontend-bootstrap#24]
In the bootstrap there is no reference/mentioning of the ```gulp task css-sassdoc```.
A missed chance, because it does add's value to the bootstrap. 
"A Documentation system to build pretty and powerful docs in the blink of an eye"

On the one hand I think it should be included in the the  ```gulp task css-watch```. 
But on the other hand sassdoc is not a task/tool/requirement for every developer.

So my suggestion is mentioning the ```gulp task css-sassdoc``` in the readme.md.

What do you guys think?

**Comment by awolkers** [comment]
We should include this within de dist task. It might be ok to mention it within the readme file

**Comment by branneman** [comment]
I'm not sure if we want this in a watcher at all, but we certainly don't want it in the `css-watch` task. If in the future there'll be a `docs-compile` and `docs-watch` task (in `docs.js`), that's where it belongs.

For now I agree with @awolkers, let's add this to the dist task.

**Comment by wouterkroes** [comment]
I don't think the ```dist``` task is the right place to add the ```css-sassdoc``` task.
Because this way you as a developer don't have a (up to date) sassdoc available.

@branneman In my current project I did add it to the ```css-watch```, for the reason is mentioned above. And then I added a /index.html file to the root of the project, with a path/link to the sassdoc page. 
I like the idea moving it from the css.js to a docs.js, because it is documentation.

So my (new) suggestion would be add a docs flow to the bootstrap and transfering sassdoc to this.
optional: create a index.html in the root of the bootstrap with a path to this sassdoc page?

**Comment by lpullersma** [comment]
I think the docs tasks mentioned by @branneman would be the logic place for this. Why not just add it? It will - for now - contain only the sassdoc, but will be extended with the other docs functionality.

**Comment by branneman** [comment]
Agreed with @lpullersma.

**Comment by wouterkroes** [comment]
Okaj, shall I make a PR to transfer sassdoc to a docs task?
Just 1 question: Should the sassdoc, in the gulp ```docs``` task, use the ```css-watch``` as a dependecy to update itself. This way keeping itself up-to-date with the scss changes OR just only generate sassdoc when running ```gulp docs```?

**Comment by branneman** [comment]
Fixed by #25
